PL/Controllers/GetAll_PController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class GetAll_PController : Controller
    {
        // GET: GetAll_P
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Popular peliculas = new ML.Popular();
            peliculas.populars = new List<Object>();

            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://api.themoviedb.org/3/");

                var responseTask = client.GetAsync("movie/popular?api_key=06a108d9592d140077cf03d529b44cfe");
                responseTask.Wait();

                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsStringAsync();
                    dynamic json = JObject.Parse(readTask.Result.ToString());

                    foreach (var resultItem in json.results)
                    {
                        ML.Popular peliList = new ML.Popular();
                        peliList.id = resultItem.id;
                        peliList.poster_path = "https://www.themoviedb.org/t/p/w600_and_h900_bestv2" + resultItem.poster_path;
                        peliList.original_title = resultItem.original_title;
                        peliList.overview = resultItem.overview;

                        peliculas.populars.Add(peliList);

                    }
                }
            }
            return View(peliculas);

        }

        public ActionResult Favorito( int media_id)
        {
            ML.Popular pelicula = new ML.Popular();
            pelicula.populars = new List<Object>();
            //ML.Result results = new ML.Result();

            using (var client = new HttpClient())
            {

                client.BaseAddress = new Uri("https://api.themoviedb.org/3/");
                string apiKey = "api_key=06a108d9592d140077cf03d529b44cfe";
                string sessionId = "session_id=f556da11090f2bf266c33b01ac0f6307e1269582";
                var value = "{ \"media_type\":\"movie\",\"media_id\": "+ media_id + ", \"favorite\": true}";
                var body= new StringContent(value, System.Text.Encoding.UTF8, "application/json");
                var responseTask = client.PostAsync("account/20430032/favorite?" + apiKey + "&" + sessionId, body);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    ViewBag.Message = "Se ha ingresado correctamente la pelicula XD";
                    return View("Modal");
                }
                else
                {
                    ViewBag.Message = "no se ingresado correctemnte la pelicula , Error: " + result.StatusCode;
                }
                //GetFavorites();
            }

            return View("GetAll");
        }

        
        [HttpGet]
        public ActionResult GetFavorites()
        {
            ML.Popular peliculas = new ML.Popular();
            peliculas.populars = new List<Object>();

            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://api.themoviedb.org/3/");

                var responseTask = client.GetAsync("account/20425861/favorite/movies?api_key=06a108d9592d140077cf03d529b44cfe&session_id=f556da11090f2bf266c33b01ac0f6307e1269582");
                responseTask.Wait();

                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsStringAsync();
                    dynamic json = JObject.Parse(readTask.Result.ToString());

                    foreach (var resultItem in json.results)
                    {
                        ML.Popular peliList = new ML.Popular();
                        peliList.id = resultItem.id;
                        peliList.poster_path = "https://www.themoviedb.org/t/p/w600_and_h900_bestv2" + resultItem.poster_path;
                        peliList.original_title = resultItem.original_title;
                        peliList.overview = resultItem.overview;

                        peliculas.populars.Add(peliList);

                    }
                }
            }
            return View(peliculas);
        }
        public ActionResult DeleteFavorito(int media_id)
        {
            ML.Popular pelicula = new ML.Popular();
            pelicula.populars = new List<Object>();
            //ML.Result results = new ML.Result();

            using (var client = new HttpClient())
            {

                client.BaseAddress = new Uri("https://api.themoviedb.org/3/");
                string apiKey = "api_key=06a108d9592d140077cf03d529b44cfe";
                string sessionId = "session_id=f556da11090f2bf266c33b01ac0f6307e1269582";
                var value = "{ \"media_type\":\"movie\",\"media_id\": " + media_id + ", \"favorite\": false}";
                var body = new StringContent(value, System.Text.Encoding.UTF8, "application/json");
                var responseTask = client.PostAsync("account/20430032/favorite?" + apiKey + "&" + sessionId, body);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    ViewBag.Message = "Se ha ingresado correctamente la pelicula";
                    return View("Modal");
                }
                else
                {
                    ViewBag.Message = "no se ingresado correctemnte la pelicula , Error: " + result.StatusCode;
                }
                //GetFavorites();
            }

            return View("GetAll");
        }

    }
}

PL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PL/Views/GetAll_P/GetAll.cshtml
@model ML.Popular
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GetAll</h2>
<body>
    <div class="container">
        <div class="row">
            @if (Model.populars != null)
            {

                foreach (ML.Popular popular in Model.populars)
                {

                    <div class="col-md-4 mb-4">
                        <div class="container-card">
                            <div class="card">
                                <a href="" target="_blank">
                                    <img class="dribbble-link" src="@popular.poster_path" style="width: 300px; height: 350px;">
                                </a>
                                <div class="contenido-card">
                                    <h3>@popular.original_title</h3>

                                    <p>@popular.overview</p>
                                    <a href="#">Leer Màs</a>
                                </div>
                                <div class="container">
                                    <a id="fav" button" class="btn btn-danger  bi bi-heart"
                                       href="@Url.Action("Favorito", "GetAll_P", new {media_id = popular.id})" );">
                                    </a>
                                </div>
                            </div>
                        </div>

                    </div>
                }

            }
            else
            {
                <div class="alert alert-danger " role="alert">
                    No encontraron peliculas registradas. Error: @ViewBag.Message;
                </div>

            }
        </div>

    </div>
</body>

@*Estilos*@

<style>


    body {
        margin: 0;
        padding: 0;
        background: #1C1A30;
        /*background-color: #353B3F;*/
        /*background: #5c746a;*/
        box-sizing: border-box;
        font-family: 'Montserrat', sans-serif;
    }
    h2 {
        color: white;
    }
    /*Cards*/
    .container-card {
        width: 100%;
        display: flex;
        max-width: 1100px;
        margin: auto;
    }

    .title-cards {
        width: 100%;
        max-width: 1080px;
        margin: auto;
        padding: 20px;
        margin-top: 20px;
        text-align: center;
        color: #7a7a7a;
    }

    .card {
        width: 100%;
        margin: 20px;
        border-radius: 6px;
        overflow: hidden;
        background: #fff;
        box-shadow: 0px 1px 10px rgba(0,0,0,0.2);
        transition: all 400ms ease-out;
        cursor: default;
    }

        .card:hover {
            box-shadow: 5px 5px 20px rgba(0,0,0,0.4);
            transform: translateY(-3%);
        }

        .card img {
            width: 100%;
            height: 210px;
        }

        .card .contenido-card {
            padding: 15px;
            text-align: center;
        }

            .card .contenido-card h3 {
                margin-bottom: 15px;
                color: #7a7a7a;
            }

            .card .contenido-card p {
                line-height: 1.8;
                color: #6a6a6a;
                font-size: 14px;
                margin-bottom: 5px;
            }

            .card .contenido-card a {
                display: inline-block;
                padding: 10px;
                margin-top: 10px;
                text-decoration: none;
                color: #2fb4cc;
                border: 1px solid #2fb4cc;
                border-radius: 4px;
                transition: all 400ms ease;
                margin-bottom: 5px;
            }

                .card .contenido-card a:hover {
                    background: #2fb4cc;
                    color: #fff;
                }

    @@media only screen and (min-width:320px) and (max-width:768px) {
        .container-card {
            flex-wrap: wrap;
        }

        .card {
            margin: 15px;
        }
    }

    .container #fav {
        position: Absolute;
        top: 4%;
        left: 5%;
        transform: translate(-30%, -50%);
        color: white;
        font-size: 1.4rem;
        width: 15%;
        height: 7%
    }
</style>

PL/Views/GetAll_P/GetFavorites.cshtml
@model ML.Popular
@{
    ViewBag.Title = "GetFavorites";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GetFavorites</h2>
<body>
    <div class="container">
        <div class="row">
            @if (Model.populars != null)
            {

                foreach (ML.Popular popular in Model.populars)
                {

                    <div class="col-md-4 mb-4">
                        <div class="container-card">
                            <div class="card">
                                <a href="" target="_blank">
                                    <img class="dribbble-link" src="@popular.poster_path" style="width: 300px; height: 350px;">
                                </a>
                                <div class="contenido-card">
                                    <h3>@popular.original_title</h3>
                                    <p>@popular.overview</p>
                                    <a href="#">Leer Màs</a>
                                </div>
                                <div class="container">
                                    <a id="fav" button" class="btn btn-danger  bi bi-heart"
                                       href="@Url.Action("DeleteFavorito", "GetAll_P", new {media_id = popular.id})" );">
                                    </a>
                                </div>
                            </div>
                        </div>

                    </div>
                }

            }
            else
            {
                <div class="alert alert-danger " role="alert">
                    No encontraron peliculas registradas. Error: @ViewBag.Message;
                </div>

            }
        </div>

    </div>
</body>

@*Estilos*@

<style>


    body {
        margin: 0;
        padding: 0;
        background: #1C1A30;
        /*background-color: #353B3F;*/
        /*background: #5c746a;*/
        box-sizing: border-box;
        font-family: 'Montserrat', sans-serif;
    }

    h2 {
        color: white;
    }
    /*Cards*/
    .container-card {
        width: 100%;
        display: flex;
        max-width: 1100px;
        margin: auto;
    }

    .title-cards {
        width: 100%;
        max-width: 1080px;
        margin: auto;
        padding: 20px;
        margin-top: 20px;
        text-align: center;
        color: #7a7a7a;
    }

    .card {
        width: 100%;
        margin: 20px;
        border-radius: 6px;
        overflow: hidden;
        background: #fff;
        box-shadow: 0px 1px 10px rgba(0,0,0,0.2);
        transition: all 400ms ease-out;
        cursor: default;
    }

        .card:hover {
            box-shadow: 5px 5px 20px rgba(0,0,0,0.4);
            transform: translateY(-3%);
        }

        .card img {
            width: 100%;
            height: 210px;
        }

        .card .contenido-card {
            padding: 15px;
            text-align: center;
        }

            .card .contenido-card h3 {
                margin-bottom: 15px;
                /*color: #7a7a7a;*/
                color: black;
                font-family: Poppins, sans-serif;
            }

            .card .contenido-card p {
                /*line-height: 1.8;
                color: #6a6a6a;
                font-size: 14px;
                margin-bottom: 5px;*/
                font-family: paragraph-font-family;
                font-size: text-movie-description;
                font-weight: regular;
                color: darken( accent-color, 30% );
                text-align: justify;
                line-height: 1.3;
            }

            .card .contenido-card a {
                display: inline-block;
                padding: 10px;
                margin-top: 10px;
                text-decoration: none;
                color: #2fb4cc;
                border: 1px solid #2fb4cc;
                border-radius: 4px;
                transition: all 400ms ease;
                margin-bottom: 5px;
            }

                .card .contenido-card a:hover {
                    background: #2fb4cc;
                    color: #fff;
                }

    @@media only screen and (min-width:320px) and (max-width:768px) {
        .container-card {
            flex-wrap: wrap;
        }

        .card {
            margin: 15px;
        }
    }

    .container #fav {
        position: Absolute;
        top: 4%;
        left: 5%;
        transform: translate(-30%, -50%);
        color: white;
        font-size: 1.4rem;
        width: 15%;
        height: 7%
    }
</style>

PL/Views/GetAll_P/Modal.cshtml
@* Modal *@

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


<div class="modal fade" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Aviso</h4>
            </div>
            <div class="modal-body">
                <p> @ViewBag.Message </p>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAll", "GetAll_P", new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal('show');
</script>

PL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

PL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

PL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Pepular Movie", "GetAll", "GetAll_P", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Favoritas Movie", "GetFavorites", "GetAll_P", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>